### ISSUE TITLE
More realistic benchmark

### ISSUE THREAD

**Issue by rickychilcott** [mediafinger/edge_benchmark_sqlite3_vs_postgresql#5]
Hey @mediafinger  - I love your benchmarking but I showed a friend who was immediately skeptical because there are no indexes set up on the associations. I did this locally and postgres fairs a lot better when the indexes exist.

Thoughts on adding those to bring it more in line with what devs would likely do?

**Comment by mediafinger** [comment]
Great idea!

I still wouldn't claim that's the queries devs usually run, but it is a sound suggestion.

Will also add a part to the README of configuring PostgresSQL so that the unix socket is being used for the connection instead the TCP socket (though the gains were not dramatic).

**Comment by mediafinger** [comment]
@rickychilcott you - and your friend - were right. It makes quite a difference as we all know. I was not aware that Postgres gains so much more from indices than SQLite. I should have included them in the beginning.

Here the new updated README:

* https://github.com/mediafinger/edge_benchmark_sqlite3_vs_postgresql?tab=readme-ov-file#results-2024-10-19-with-indices-on-the-foreign-keys

**Comment by rickychilcott** [comment]
This was @phil-monroe pointing this out. 

Thanks for these. Sqlite is STILL faster (and that's without any network latency), so it's still a worthwhile benchmark. It's actually cool to know that sqlite covers over a lack of indexes that would help new developers ship more performant applications, even if unintentionally.
